all:
  vars:
    users:
      iv:
        name: "iv"
        ssh_private_key_file: "/home/iv/.ssh/id_ed25519.pub"
    # ansible_ssh_user: "iv"
    # ansible_ssh_private_key_file: "{{ users[iv].ssh_private_key_file }}"
  children:
    omnitell:
      hosts:
        fs_omnitell_ru:
          ansible_host: "fs.omnitell.ru"
          ansible_port: 9229
          ansible_user: "{{ vars.users.iv.name }}"
          ansible_ssh_private_key_file: "{{ vars.users.iv.ssh_private_key_file }}"
