---
- name: Freeswitch-Autocalling-Frontend
  hosts: fs_omnitell_ru
  vars:
    pm2_service_names: {
      prod: 'Autocalling-Frontend',
      dev: 'Autocalling-Frontend-dev'
    }
    local_repo: '/home/iv/Documents/mydir/work/freeswitch'
    local_path: '/home/iv/Documents/mydir/vuejs/autocalling-frontend'
    local_path_backend_mockery: '/home/iv/Documents/mydir/vuejs/fullstack-vue/simple-backend'
    dest_path: {
      prod: '/opt/autocalling-frontend/prod',
      dev: '/opt/autocalling-frontend/dev',
      backend_mockery: '/opt/mocks/for-acall-front',
      static_storage: '/var/www/html'
    }
  become: true
  tasks:
    - name: Canary copy
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: iv
        group: iv
      with_items:
      - {
          src: "{{ vars.local_path }}/package.json",
          dest: "{{ dest_path.dev }}"
        }
      - {
          src: "{{ vars.local_path }}/public",
          dest: "{{ dest_path.dev }}"
        }
      - {
          src: "{{ vars.local_path }}/src",
          dest: "{{ dest_path.dev }}"
        }
      - {
          src: "{{ vars.local_path }}/ecosystem.dev.config.js",
          dest: "{{ dest_path.dev }}"
        }
      - {
          src: "{{ vars.local_path }}/vue.config.js",
          dest: "{{ dest_path.dev }}"
        }
      - {
          src: "{{ vars.local_path }}/babel.config.js",
          dest: "{{ dest_path.dev }}"
        }
      - {
          src: "{{ vars.local_path }}/env-for-dev",
          dest: "{{ dest_path.dev }}/.env.production"
        }
      - {
          src: "{{ vars.local_path }}/key.pem",
          dest: "{{ dest_path.dev }}/"
        }
      - {
          src: "{{ vars.local_path }}/cert.pem",
          dest: "{{ dest_path.dev }}/"
        }

    - name: Sync backend mock
      copy: 
        src: "{{ item }}"
        dest: "{{ dest_path.backend_mockery }}"
      with_items:
      - "{{ local_path_backend_mockery }}/index.js"
      - "{{ local_path_backend_mockery }}/package.json"
      - "{{ local_path_backend_mockery }}/tsconfig.json"
      - "{{ local_path_backend_mockery }}/ecosystem.config.js"

    - name: Refresh packages for dev
      shell: |
        source ~/.bashrc
        nvm use 21
        npm install
        npm install serve
      args:
        executable: /bin/bash
        chdir: "{{ dest_path.dev }}"

    - name: Refresh packages for backend-mockery
      shell: |
        source ~/.bashrc
        nvm use 21
        npm install
      args:
        executable: /bin/bash
        chdir: "{{ dest_path.backend_mockery }}"

    - name: Build prj
      shell: |
        source ~/.bashrc
        nvm use 21
        export BUILDING_FOR="dev"
        npm run build
      args:
        executable: /bin/bash
        chdir: "{{ dest_path.dev }}"

    - name: Copy static files to standard storage
      ansible.builtin.copy:
        remote_src: true
        src: '{{ dest_path.dev }}/dist/'
        dest: '{{ dest_path.static_storage }}/autocalling-dev'





