---
- name: Freeswitch-Autocalling-Backend
  hosts: fs_omnitell_ru
  vars:
    pm2_service_names: 'Autocalling-MRG'
    local_repo: '/home/iv/Documents/mydir/work/freeswitch'
    remote_path: '/opt/autocalling-mrg/server-side'
    local_path: '/home/iv/Documents/mydir/work/freeswitch/opt/autocalling-mrg/server-side'

  become: true
  tasks:
    # - name: Mark copyable files
    #   find:
    #     paths: "{{ local_path }}"
    #     hidden: true
    #     recurse: true
    #     excludes: "node_modules,dist"
    #   delegate_to: localhost
    #   register: copyable_files
    #   remote_user: root

    - name: Sync package.json
      ansible.builtin.copy:
        src: "{{ vars.local_path }}/package.json"
        dest: "{{ vars.remote_path }}"
      notify:
        - Refresh packages

    - name: Sync files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        # owner: iv
        # group: iv
      with_items:
      - {
          src: "{{ vars.local_path }}/src",
          dest: "{{ remote_path }}"
        }
      - {
          src: "{{ vars.local_path }}/ecosystem.config.js",
          dest: "{{ remote_path }}"
        }
      - {
          src: "{{ vars.local_path }}/tsconfig.json",
          dest: "{{ remote_path }}"
        }
      - {
          src: "{{ vars.local_path }}/tsconfig.build.json",
          dest: "{{ remote_path }}"
        }
      - {
          src: "{{ vars.local_path }}/test",
          dest: "{{ remote_path }}"
        }
      notify:
        - Build prj
        - Restart pm2 daemon





  handlers:
    - name: Refresh packages
      shell: |
        source ~/.bashrc
        nvm use 21
        npm install
      args:
        executable: /bin/bash
        chdir: "{{ remote_path }}"

    - name: Build prj
      shell: |
        source ~/.bashrc
        nvm use 21
        npm run build
      args:
        executable: /bin/bash
        chdir: "{{ remote_path }}"

    - name: Restart pm2 daemon
      shell: pm2 restart {{ pm2_service_names }}









